# Generated by Django 4.1.7 on 2023-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='devolucao',
            field=models.BooleanField(default=False, verbose_name='Devolvido'),
            preserve_default=False,
        ),
    ]
